# Generated by Django 4.2.1 on 2023-05-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Branches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("DOB", models.DateField()),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("U", "Unisex/Parody"),
                        ],
                        max_length=1,
                    ),
                ),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                (
                    "materials_provided",
                    models.CharField(
                        choices=[
                            ("debit card", "DEBIT CARD"),
                            ("credit card", "CREDIT CARD"),
                            ("cheque", "CHEQUE"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bankapp.account",
                    ),
                ),
                (
                    "District",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bankapp.district",
                    ),
                ),
                (
                    "branches",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bankapp.branches",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="branches",
            name="branches",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bankapp.district"
            ),
        ),
    ]
